inputCharset: "GBK"
outputCharset: "GBK"

terminals:
  PowerShell:
    name: "PowerShell"
    startCommand: "powershell"
    workspace: "."
  HamsterService:
    name: "HamsterService"
    startCommand: "java -jar HamsterService.jar"
    workspace: "D:\\MinecraftServer\\HamsterService"
